version: '3'

networks:
  redbellnetwork:
    driver: bridge

services:
    node:
        image: registry.cn-shenzhen.aliyuncs.com/yxw-docker/node10.15.3:latest
        container_name: node
        hostname: node
        networks:
          - redbellnetwork
        ports:
            - "7100:7100"
        working_dir: /source/bs-ccr-node
        links:
            - redis:redis
            - node-huobi:node-huobi
        volumes:
            - /source/bs-ccr-node:/source/bs-ccr-node
            - /Users/sivan/Library/Caches/Yarn/v4:/usr/local/share/.cache/yarn/v4
        command: ["/bin/sh", "-c", "yarn install && yarn dev"]

